###
GET http://localhost:3000/customers HTTP/1.1


###
POST http://localhost:3000/customers HTTP/1.1
content-type: application/json

{
    "name":"Jenny",
    "email":"jenny.gmail.com",
    "age":32
}

###
DELETE http://localhost:3000/customer/1 HTTP/1.1

###
PUT http://localhost:3000/customer/1 HTTP/1.1
Content-Type: application/json

{
    "name":"Jenny",
    "email":"jenny.gmail.com",
    "age":22
}

